adj = input("digite um adjetivo no plural no feminino:")
noun = input("digite um substantivo no plural:")
adverb = input("digite um advérbio:")
print("rosas são "+ str(adj))
print(str(noun)+ " são violetas")
print("e o mundo está fazendo "+ str(adverb))
